"""Initial

Revision ID: e988e2180d91
Revises: 
Create Date: 2025-06-19 15:30:53.346617

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e988e2180d91'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('book',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('mytest')
    op.drop_table('mystest')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mystest',
    sa.Column('name', sa.VARCHAR(length=80), autoincrement=False, nullable=True),
    sa.Column('amount', sa.SMALLINT(), autoincrement=False, nullable=False)
    )
    op.create_table('mytest',
    sa.Column('name', sa.VARCHAR(length=80), autoincrement=False, nullable=True)
    )
    op.drop_table('book')
    # ### end Alembic commands ###
